// Code generated by mockery v1.0.0. DO NOT EDIT.

package main

import mock "github.com/stretchr/testify/mock"

// PlayerStore is an autogenerated mock type for the PlayerStore type
type MockeryPlayerStore struct {
	mock.Mock
}

// GetLeague provides a mock function with given fields:
func (_m *MockeryPlayerStore) GetLeague() []Player {
	ret := _m.Called()

	var r0 []Player
	if rf, ok := ret.Get(0).(func() []Player); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]Player)
		}
	}

	return r0
}

// GetPlayerScore provides a mock function with given fields: name
func (_m *MockeryPlayerStore) GetPlayerScore(name string) int {
	ret := _m.Called(name)

	var r0 int
	if rf, ok := ret.Get(0).(func(string) int); ok {
		r0 = rf(name)
	} else {
		r0 = ret.Get(0).(int)
	}

	return r0
}

// RecordWin provides a mock function with given fields: name
func (_m *MockeryPlayerStore) RecordWin(name string) {
	_m.Called(name)
}
